### ISSUE TITLE
Documentation improvements

### ISSUE THREAD

**Issue by eyalbe4** [hanochg/piperika#10]
Great plugin Team!

Here are some suggestions for improving the README documentation, becuase I'm not sure people will manage to start using the plugin immediately without these additions.

1. The README should include instructions for how to configure the details of your JFrog Pipelines envirobment.
2. I suggest adding a sample of the output after runnijg the ```run``` command.
3. Since people are going to install and then use the plugin through JFrog CLI, I suggest that the usage example looks like ```jf piperika run```.
4. Since the plugin will be published to the public registry rught after to apply some (or all) of the improvements to the README, I suggest you already add the ```jf plugin install piperika``` command to the README (see the README of other plugins included in the regitry).
5. The image in the README is amazing. I would consider however making it a little bit smaller, but if you like it at its cyrrent size, feel free to leave it as is.

**Comment by hanochg** [comment]
Thanks for the feedback!
I added everything you mentioned with a small leftover, the Pipelines configuration instructions will be enriched once we will complete the task of exporting the Pipelines configurations to a configuration file (instead of being hard-coded).

**Comment by eyalbe4** [comment]
Great! Thanks @hanochg .
